### PR TITLE
Update to Ecto 2.0.0-rc

### PR DESCRIPTION
**Pull request by bjz**
Based off #35, I've updated Scrivener to use the latest release candidate of Ecto. I realise however that it will probably be hard to get this merged, seeing as you would probably have to do a major release, but hopefully others might find this useful if they would like to test their apps against Ecto 3 in the interim.

### CODE REVIEW

**Comment by drewolson** [comment]
Hi @bjz. I already support Ecto 2.0 on the [v2](https://github.com/drewolson/scrivener/tree/v2) branch and in the [Scrivener.Ecto](https://github.com/drewolson/scrivener_ecto) library. I plan on merging in `v2` when Ecto 2.0 is released.

Thanks.

**Comment by bjz** [comment]
Oh nice! Didn't notice that branch!

**Comment by drewolson** [comment]
You're not the first :) I'll add something to the master branch README.

Thanks!

**Comment by bjz** [comment]
I'm wondering if it might help to keep this issue open, then close it when v2 is merged? Might make it clearer to see what is going on, and what the timeline is. But yes, an addition to the README could clear things up as well.

**Comment by drewolson** [comment]
@bjz good point, will do.

**Comment by drewolson** [comment]
Closing this PR now that I've added a note to the README.

**Pull request closed without merging**
