### PR TITLE
use database asterisk wildcard to count instead of the id column

### PR DESCRIPTION
**Pull request by eikes**

### CODE REVIEW

**Comment by drewolson** [comment]
@eikes thanks for the PR! Would you mind adding some test coverage before I pull this in? Perhaps you could add a test model that uses a non-standard primary key.

**Comment by eikes** [comment]
Sure. Here you go.

**Comment by drewolson** [comment]
Great, thanks! Merged.

**Comment by drewolson** [comment]
These changes have been included in the new release on hex, version 0.7.1. Thanks again!

**Pull request merged**
