### PR TITLE
Start on making link pagination easier for the view layer. Needs tests.

### PR DESCRIPTION
**Pull request by mgwidmann**
After seeing an elixir-sips episode using this tool, I thought it was a shame that it didn't have a simpler tool for printing the view layer.

I've still got a bit more work to do on it, but I wanted to get it out there and see what your thoughts were on what I started.

@knewter :+1:

### CODE REVIEW

**Comment by drewolson** [comment]
Thanks for this, I thought the same thing when I saw the video. A few thoughts.

* I think we should put it in the module `Scrivener.HTML` to be consistent with phoenix
* I'd prefer the function be called `pagination_links`
* While your code[1] works in the naive case, users may need to pass other options when generating the link other than just the page number.
* We may want to think about an API closer to Scrivener itself. Perhaps you'd mix this into your view

```elixir
defmodule MyApp.View do
  use Scrivener.HTML, # options go here, like window size, etc
end
```

This would generate a `pagination_links` function on your view module that would be accessible from templates.

Finally, if this goes well I'll probably eventually pull it out to a separate package `scrivener_html`, again for consistency with phoenix.

Thoughts?

[1] - https://github.com/drewolson/scrivener/pull/8/files#diff-8b9bf4af357da1cb11dacde83dc1ede2R25

**Comment by drewolson** [comment]
To give you an idea of how I do this in my projects, here are some snippets:

```elixir
defmodule MyApp.Helper.Pagination do
  def pagination_path({path_fn, [conn, action]}, pagination_options) do
    pagination_path({path_fn, [conn, action, []]}, pagination_options)
  end

  def pagination_path({path_fn, [conn, action, options]}, pagination_options) do
    apply(MyApp.Router.Helpers, path_fn, [conn, action, Dict.merge(options, pagination_options)])
  end
end
```

```elixir
<%= render MyApp.SharedView, "_pagination.html", page: @page, path: {:employee_path, [@conn, :index, [archived: @archived]]} %>
```

```eex
<div>
  <%= unless @page.page_number == 1 do %>
    <%= link "Previous Page", to: pagination_path(@path, page_size: @page.page_size, page: @page.page_number - 1), class: "btn" %>
  <% end %>

  <%= unless @page.page_number == @page.total_pages do %>
    <%= link "Next Page", to: pagination_path(@path, page_size: @page.page_size, page: @page.page_number + 1), class: "btn" %>
  <% end %>
</div>
```

**Comment by mgwidmann** [comment]
Great! I was thinking a lot of the same things. I realize the need for many more options like you mentioned, including the function for generating the link properly instead of doing "?page=...". I want to expose the function which returns the list of tuple pairs to allow creating the links manually easier, with whatever css framework. 

I'll keep working on it!

**Comment by mgwidmann** [comment]
I added a bunch of tests and documentation as well as refactored it a bit to read easier. 

For the moment, the `path` function and its arguments (via `path_args`) are just options passed into the function. I think, since we have the pagination struct, we should be able to detect the `path` function for them. 

I still want to add a few more tests, but wanted to get your feedback on how its coming so far...

**Comment by drewolson** [comment]
Thanks for the updates. I've got a busy week, so I probably won't get to looking at this until this weekend. Would you mind rebasing this onto master? I've made some updates to be compatible with the latest ecto release.

**Comment by mgwidmann** [comment]
Sure np, I'll get to it before tonight.

**Comment by drewolson** [comment]
@mgwidmann I've thought quite a bit about this. At this point, I think if you're interesting in publishing this functionality, you should do so under your own repo and package dedicated to the html side of scrivener.

I'd prefer to keep scrivener light-weight and agnostic of templates / rendering. If you do end up publishing something, please let me know and I'd gladly add it to a "related projects" section of the wiki.

Hope this makes sense.

**Pull request closed without merging**
