### PR TITLE
Make sure page number is always positive

### PR DESCRIPTION
**Pull request by krishandley**
Update from #42

### CODE REVIEW

**Comment by drewolson** [comment]
Great start. Would you also mind defaulting `page_size` to the default size if negative?

**Comment by krishandley** [comment]
Updated but realised after pushing I put it to 1 not the max page size!

**Comment by drewolson** [comment]
I ended up implementing this in a slightly different way on master. Gave you a shout out in the commit :)

Thanks!

**Comment by krishandley** [comment]
Thanks, and no problem, just glad I can remove a bit of code from my app now :)

**Pull request closed without merging**
