### PR TITLE
Fix total entries when none is found

### PR DESCRIPTION
**Pull request by mkaszubowski**

### CODE REVIEW

**Comment by mkaszubowski** [comment]
I'm not sure if the PR is correct since the only option was to merge to master. Please correct me if I'm wrong. 
It's quite late in my timezone, so I'll send a PR for scrivener_ecto tomorrow if that's alright.

**Comment by drewolson** [comment]
@mkaszubowski thanks! I'll update the base branch now to a newly created `v1.2` branch.

**Comment by mkaszubowski** [comment]
@drewolson  I'd really appreciate it if you released it as `1.2.2` to hex. Are you maybe planning to do this?

**Comment by drewolson** [comment]
Yes, I'll do so today. Sorry for the delay!

**Comment by drewolson** [comment]
I've release `1.2.2`. Thanks for the PR!

**Comment by mkaszubowski** [comment]
My pleasure 😄  Thanks for the quick release!

**Pull request merged**
